Import fix (#1083)
Changing the import from `from jose import jwt` to `import jose`
introduced errors like:

AttributeError: module 'jose' has no attribute 'jwt'